export type Access = "free" | "mixed";
export type Progress = "planned" | "in-progress" | "completed" | "paused";

export interface Resource {
  name: string;
  url: string;
  kind: string;
  note: string;
}

export interface Course {
  id: string;
  number: string;
  title: string;
  provider: string;
  access: Access;
  duration: string;
  effort: string;
  summary: string;
  why: string;
  topics: string[];
  project: string;
  mastery: string;
  resources: Resource[];
  prerequisites: string[];
  optionalFrom?: string[];
  progress: Progress;
  position: { x: number; y: number };
}

export const githubRepo = "chukynya/learning-guide";
export const canvas = { width: 1320, height: 2700 };

export const phases = [
  { label: "00 · Finish what you started", top: 24 },
  { label: "01 · Build the foundations", top: 338 },
  { label: "02 · Understand the machine", top: 904 },
  { label: "03 · Specialize without skipping layers", top: 1470 },
  { label: "04 · Measure, question, improve", top: 2325 },
];

export const courses: Course[] = [
  {
    id: "missing-semester",
    number: "00.1",
    title: "The Missing Semester",
    provider: "MIT CSAIL",
    access: "free",
    duration: "2 weeks",
    effort: "5 h/week",
    summary: "Make Linux, the shell, Git, debugging, and profiling feel like instruments—not magic incantations.",
    why: "If Linux or serious command-line work is new, finish this first so every later course happens in an environment you can inspect and repair.",
    topics: [
      "Shell composition, jobs, signals, and data wrangling",
      "Editor, terminal, and development environment",
      "Debuggers, profilers, tracing, and logs",
      "Git's object model, history, branches, and recovery",
      "Packaging, shipping, code quality, and security basics",
    ],
    project: "Create a reproducible dotfiles repository plus a one-command setup that is safe to run twice on a fresh Linux VM.",
    mastery: "You can diagnose a broken command, inspect a process, recover a Git mistake, and explain each command in your setup script.",
    resources: [
      {
        name: "2026 course",
        url: "https://missing.csail.mit.edu/",
        kind: "Lectures + notes",
        note: "Use the newest self-contained offering; revisit 2020 for data wrangling and security.",
      },
    ],
    prerequisites: [],
    progress: "in-progress",
    position: { x: 220, y: 112 },
  },
  {
    id: "composing-programs",
    number: "00.2",
    title: "Composing Programs",
    provider: "UC Berkeley · John DeNero",
    access: "free",
    duration: "8 weeks",
    effort: "6 h/week",
    summary: "Learn abstraction, data, interpreters, and computation using Python as the notation rather than the destination.",
    why: "Syntax knowledge is not enough. Learn abstraction and evaluation first, then use software-construction practice to make programs testable, understandable, and safe to change.",
    topics: [
      "Functions, recursion, higher-order functions, and abstraction",
      "Data abstraction, mutation, objects, and efficiency",
      "Environments, evaluation, interpreters, and exceptions",
      "Declarative, logic, distributed, and parallel computation",
      "Program design through the official projects",
      "Specifications, tests, representation invariants, and code review",
    ],
    project: "Finish the Scheme interpreter, draw five non-trivial environment diagrams, then add a specification, principled tests, and a code review to one earlier project.",
    mastery: "You can explain evaluation, choose an abstraction intentionally, specify its behavior, test its boundaries, and change it without breaking clients.",
    resources: [
      {
        name: "Composing Programs",
        url: "https://www.composingprograms.com/",
        kind: "Interactive text + projects",
        note: "Free, complete, and directly connected to Berkeley CS 61A material.",
      },
      {
        name: "MIT 6.102 Software Construction",
        url: "https://web.mit.edu/6.102/www/sp26/",
        kind: "Current readings + exercises",
        note: "After the interpreter, use readings 2–8 and one problem set for testing, specifications, abstract data types, and code review.",
      },
    ],
    prerequisites: [],
    progress: "in-progress",
    position: { x: 720, y: 112 },
  },
  {
    id: "linux-internals",
    number: "01.1",
    title: "Linux From the Inside",
    provider: "Linux From Scratch",
    access: "free",
    duration: "6 weeks",
    effort: "5 h/week",
    summary: "Move from using Linux to understanding boot, filesystems, processes, permissions, packages, and the user/kernel boundary.",
    why: "Changing OS is useful only if you inspect the layers. Building a small Linux system makes package managers and distributions concrete.",
    topics: [
      "Boot chain, kernel, init, services, and system logs",
      "Filesystem hierarchy, mounts, devices, /proc, and /sys",
      "Users, groups, capabilities, permissions, and namespaces",
      "Toolchains, linking, libraries, packages, and reproducible builds",
      "Processes, signals, resource limits, and system calls",
    ],
    project: "Build Linux From Scratch inside a disposable VM and publish an annotated diagram from firmware to the first user process.",
    mastery: "You can locate where a Linux behavior comes from and explain the difference between the kernel, distribution, shell, service manager, and desktop.",
    resources: [
      {
        name: "Linux From Scratch",
        url: "https://www.linuxfromscratch.org/lfs/",
        kind: "Book + build instructions",
        note: "Use a VM or container host; never experiment on the machine holding your only copy of important files.",
      },
    ],
    prerequisites: ["missing-semester"],
    progress: "planned",
    position: { x: 70, y: 408 },
  },
  {
    id: "c-foundations",
    number: "01.2",
    title: "C & Memory",
    provider: "Modern C · Beej",
    access: "free",
    duration: "4–8 weeks",
    effort: "7 h/week",
    summary: "Turn basic C familiarity into a precise model of memory, compilation, linking, undefined behavior, and operating-system interfaces.",
    why: "Prior C coursework is a head start, not a reason to replay syntax. Attempt the project first, then study only gaps in memory, undefined behavior, linking, debugging, and POSIX interfaces.",
    topics: [
      "Object representation, integer behavior, pointers, arrays, and strings",
      "Stack, heap, ownership conventions, allocation, and lifetime",
      "Translation units, preprocessing, object files, static and dynamic linking",
      "File I/O, processes, sockets, and the POSIX boundary",
      "gdb, sanitizers, Valgrind, make, warnings, and defensive interfaces",
    ],
    project: "From scratch, build a generic vector and hash table, then use them in a small command-line indexer with sanitizer-clean tests.",
    mastery: "You can draw the memory layout, explain every allocation and free, inspect the binary, and fix a crash from evidence rather than guessing.",
    resources: [
      {
        name: "Modern C · C23 edition",
        url: "https://gustedt.gitlabpages.inria.fr/modern-c/",
        kind: "Free book + code",
        note: "Use the current C23 edition as the main bridge from university C to portable systems programming.",
      },
      {
        name: "Beej's Guide to C Programming",
        url: "https://beej.us/guide/bgc/",
        kind: "Book",
        note: "Written for people who already know another language; free HTML and downloads.",
      },
      {
        name: "Beej's Guide to Network Programming",
        url: "https://beej.us/guide/bgnet/",
        kind: "Reference + examples",
        note: "Use the early socket chapters after file I/O and processes.",
      },
    ],
    prerequisites: ["missing-semester", "composing-programs"],
    progress: "in-progress",
    position: { x: 370, y: 408 },
  },
  {
    id: "discrete-math",
    number: "01.3",
    title: "Mathematics for CS",
    provider: "MIT 6.1200J",
    access: "free",
    duration: "8 weeks",
    effort: "6 h/week",
    summary: "Learn to define, prove, count, and reason about the discrete objects that algorithms and systems are built from.",
    why: "The goal is not more formulas. It is the ability to tell whether an idea is true, state its assumptions, and prove where it stops working.",
    topics: [
      "Logic, sets, relations, functions, and proof structure",
      "Induction, contradiction, invariants, state machines, and recursion",
      "Graphs, trees, walks, matching, and partial orders",
      "Asymptotics, recurrences, elementary number theory, and cryptography",
      "Counting, combinatorics, and discrete probability",
    ],
    project: "Keep a proof notebook: one polished proof and one counterexample per topic, each reviewed after a week without notes.",
    mastery: "You can write a proof that another student can audit and identify the invariant or counterexample behind an algorithmic claim.",
    resources: [
      {
        name: "MIT Mathematics for Computer Science",
        url: "https://ocw.mit.edu/courses/6-1200j-mathematics-for-computer-science-spring-2024/",
        kind: "Videos + notes + problem sets",
        note: "Use the problem sets as the course; videos alone are not completion.",
      },
    ],
    prerequisites: ["composing-programs"],
    progress: "planned",
    position: { x: 670, y: 408 },
  },
  {
    id: "linear-algebra",
    number: "01.4",
    title: "Linear Algebra",
    provider: "MIT 18.06SC",
    access: "free",
    duration: "4–8 weeks",
    effort: "6 h/week",
    summary: "Build geometric and algebraic intuition for vectors, linear maps, eigensystems, least squares, and the matrices inside ML.",
    why: "Use the MIT exams to place out of familiar university material. Spend time only where geometric intuition, proofs, least squares, eigensystems, or SVD remain weak.",
    topics: [
      "Systems of equations, elimination, rank, and factorization",
      "Vector spaces, bases, dimension, and the four fundamental subspaces",
      "Orthogonality, projections, least squares, and QR",
      "Determinants, eigenvalues, eigenvectors, and diagonalization",
      "Positive definite matrices, SVD, pseudoinverse, and applications",
    ],
    project: "Implement elimination, least squares, PCA, and a tiny image compressor using only Python lists first, then verify with NumPy.",
    mastery: "You can predict shapes, rank, null spaces, and failure modes before asking a numerical library for an answer.",
    resources: [
      {
        name: "MIT 18.06SC Linear Algebra",
        url: "https://ocw.mit.edu/courses/18-06sc-linear-algebra-fall-2011/",
        kind: "Videos + notes + exams",
        note: "Take an exam first as a diagnostic, then complete exercises only for the units that expose gaps.",
      },
    ],
    prerequisites: ["composing-programs"],
    progress: "in-progress",
    position: { x: 970, y: 408 },
  },
  {
    id: "nand2tetris",
    number: "01.5",
    title: "Nand to Tetris · Part I",
    provider: "Nand2Tetris",
    access: "free",
    duration: "6 weeks",
    effort: "7 h/week",
    summary: "Build a working computer from NAND gates through ALU, memory, CPU, machine language, and assembler.",
    why: "This removes the vague boundary called hardware. Every abstraction later in the roadmap lands on something you have assembled yourself.",
    topics: [
      "Boolean logic and combinational chips",
      "Arithmetic circuits, ALU, and two's-complement representation",
      "Registers, RAM, program counters, and sequential logic",
      "Instruction sets, CPU datapaths, and memory-mapped I/O",
      "Assembler design and hardware/software contracts",
    ],
    project: "Complete official projects 1–6 locally and write the assembler without copying a reference implementation.",
    mastery: "You can trace one high-level operation down to instructions, registers, gates, and state transitions.",
    resources: [
      {
        name: "Nand2Tetris official course",
        url: "https://www.nand2tetris.org/",
        kind: "Lectures + tools + projects",
        note: "The official site materials are free; Coursera is only needed for a paid certificate.",
      },
    ],
    prerequisites: ["c-foundations"],
    progress: "completed",
    position: { x: 70, y: 678 },
  },
  {
    id: "algorithms",
    number: "01.6",
    title: "Algorithms & Data Structures",
    provider: "MIT 6.006",
    access: "free",
    duration: "6–10 weeks",
    effort: "8 h/week",
    summary: "Move beyond solving familiar DSA exercises: model the problem, prove correctness, and measure the implementation.",
    why: "Prior algorithms coursework counts. Start with Problem Set 0 and an unfamiliar proof; study only gaps in modeling, correctness, amortized analysis, and measurement.",
    topics: [
      "Models of computation, asymptotic analysis, and problem reduction",
      "Dynamic arrays, linked structures, hashing, heaps, and balanced trees",
      "Sorting, selection, graph search, shortest paths, and topological order",
      "Divide-and-conquer, greedy reasoning, and dynamic programming",
      "Correctness proofs, amortized analysis, benchmarks, and trade-offs",
    ],
    project: "Complete selected 6.006 problem sets and implement one structure in both C and Python with a benchmark and complexity report.",
    mastery: "For an unfamiliar problem, you can state the model, derive the algorithm, prove it, analyze it, and test the real performance.",
    resources: [
      {
        name: "MIT 6.006 Introduction to Algorithms",
        url: "https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/",
        kind: "Videos + notes + assignments",
        note: "Start with Problem Set 0; it exposes missing prerequisites early.",
      },
    ],
    prerequisites: ["composing-programs", "discrete-math"],
    progress: "in-progress",
    position: { x: 370, y: 678 },
  },
  {
    id: "probability",
    number: "01.7",
    title: "Probability",
    provider: "Harvard Stat 110",
    access: "free",
    duration: "9 weeks",
    effort: "7 h/week",
    summary: "Learn to reason about uncertainty, conditional information, distributions, expectation, limit laws, and stochastic processes.",
    why: "ML evaluation, risk, fraud, experiments, and performance measurements all fail when probability intuition is weak.",
    topics: [
      "Counting, sample spaces, conditional probability, and Bayes' rule",
      "Random variables, PMFs/PDFs, expectation, variance, and covariance",
      "Common discrete and continuous distributions",
      "Joint distributions, conditioning, transformations, and independence",
      "Law of large numbers, central limit theorem, and Markov chains",
    ],
    project: "Build a simulation notebook that verifies ten results, then explain where simulation agrees slowly or misleads.",
    mastery: "You can choose a probability model, condition correctly, calculate uncertainty, and distinguish an estimate from evidence.",
    resources: [
      {
        name: "Harvard Stat 110",
        url: "https://stat110.hsites.harvard.edu/",
        kind: "Lectures + practice sets",
        note: "Solve the strategic practice problems before reading solutions.",
      },
    ],
    prerequisites: ["discrete-math", "linear-algebra"],
    progress: "planned",
    position: { x: 670, y: 678 },
  },
  {
    id: "numerical-computing",
    number: "01.8",
    title: "Calculus & Numerical Computing",
    provider: "MIT OCW · NumPy",
    access: "free",
    duration: "8 weeks",
    effort: "6 h/week",
    summary: "Connect derivatives and multivariable calculus to finite-precision arrays, stable algorithms, optimization, and reproducible experiments.",
    why: "Modern ML courses assume the chain rule, gradients, and linear algebra. Learn those mechanisms before trusting automatic differentiation or an optimizer.",
    topics: [
      "Derivatives, chain rule, partial derivatives, gradients, Jacobians, Hessians, and Taylor approximation",
      "Floating-point representation, conditioning, stability, and error",
      "Array shapes, strides, broadcasting, vectorization, and memory layout",
      "Matrix factorizations, least squares, PCA, and iterative methods",
      "Gradients, finite differences, optimization, and automatic differentiation",
      "Reproducible experiments, seeds, baselines, and numerical tests",
    ],
    project: "Derive and gradient-check linear regression, implement stable regression and PCA, then explain every accuracy and performance difference between loops and vectorized code.",
    mastery: "You can derive gradients, detect an ill-conditioned operation, design a numerical check, and identify whether speed came from algorithm, vectorization, or hardware.",
    resources: [
      {
        name: "MIT 18.01SC Single Variable Calculus",
        url: "https://ocw.mit.edu/courses/18-01sc-single-variable-calculus-fall-2010/",
        kind: "Videos + problems + exams",
        note: "Use the differentiation, optimization, Newton's method, and Taylor-series units; skip familiar material by passing its exam.",
      },
      {
        name: "MIT 18.02SC Multivariable Calculus",
        url: "https://ocw.mit.edu/courses/18-02sc-multivariable-calculus-fall-2010/",
        kind: "Videos + problems + exams",
        note: "Prioritize partial derivatives, the chain rule, gradients, directional derivatives, and constrained optimization.",
      },
      {
        name: "MIT 18.065 Matrix Methods",
        url: "https://ocw.mit.edu/courses/18-065-matrix-methods-in-data-analysis-signal-processing-and-machine-learning-spring-2018/",
        kind: "Videos + notes",
        note: "Focus on the linear algebra used in data analysis and ML.",
      },
      {
        name: "NumPy fundamentals",
        url: "https://numpy.org/learn/",
        kind: "Official tutorials",
        note: "Use NumPy only after implementing the small examples directly.",
      },
    ],
    prerequisites: ["composing-programs", "linear-algebra"],
    progress: "planned",
    position: { x: 970, y: 678 },
  },
  {
    id: "computer-architecture",
    number: "02.1",
    title: "Computer Architecture",
    provider: "UC Berkeley CS 61C",
    access: "free",
    duration: "8 weeks",
    effort: "8 h/week",
    summary: "Study how C becomes instructions and how processors, caches, parallelism, and storage make programs fast or slow.",
    why: "Efficiency claims are empty unless you understand the machine executing the code.",
    topics: [
      "C memory model, assembly, calling conventions, and RISC-V",
      "Datapaths, pipelining, hazards, and instruction-level parallelism",
      "Caches, locality, virtual memory, and memory hierarchy",
      "SIMD, multithreading, synchronization, and data-level parallelism",
      "Performance measurement, energy, dependability, and trade-offs",
    ],
    project: "Build a RISC-V emulator or cache simulator and use it to explain the cost of two equivalent C implementations.",
    mastery: "You can follow data from C source through assembly and the memory hierarchy, then predict likely bottlenecks.",
    resources: [
      {
        name: "Berkeley CS 61C",
        url: "https://cs61c.org/?redirect=false",
        kind: "Notes + labs + projects",
        note: "Use the public current course entry and notes; avoid semester archive paths that require a Berkeley login.",
      },
    ],
    prerequisites: ["c-foundations", "nand2tetris"],
    progress: "planned",
    position: { x: 70, y: 974 },
  },
  {
    id: "operating-systems",
    number: "02.2",
    title: "Operating Systems",
    provider: "OSTEP · UW–Madison",
    access: "free",
    duration: "10 weeks",
    effort: "8 h/week",
    summary: "Understand the abstractions and mechanisms behind processes, memory, concurrency, filesystems, I/O, and security.",
    why: "Linux stops being one opaque product when you can explain which OS abstraction created the behavior you observe.",
    topics: [
      "Processes, system calls, scheduling, context switching, and signals",
      "Address spaces, paging, TLBs, allocation, and virtual memory policies",
      "Threads, locks, condition variables, semaphores, and concurrency bugs",
      "Devices, disks, filesystems, journaling, integrity, and persistence",
      "Authentication, access control, cryptography, and isolation",
    ],
    project: "Complete OSTEP simulators plus one systems project: a shell, user-level threads, or a small filesystem with crash tests.",
    mastery: "You can trace a program's use of CPU, memory, and storage through OS mechanisms and reproduce a race or persistence failure.",
    resources: [
      {
        name: "Operating Systems: Three Easy Pieces",
        url: "https://pages.cs.wisc.edu/~remzi/OSTEP/",
        kind: "Free chapters + projects",
        note: "Read by concept, then run the matching official simulator or project.",
      },
    ],
    prerequisites: ["c-foundations", "computer-architecture"],
    progress: "planned",
    position: { x: 370, y: 974 },
  },
  {
    id: "computer-networks",
    number: "02.3",
    title: "Computer Networks",
    provider: "Stanford CS 144",
    access: "free",
    duration: "8 weeks",
    effort: "8 h/week",
    summary: "Build the internet upward from packets: reliable transport, routing, naming, congestion, sockets, and application protocols.",
    why: "Backend and distributed systems are networking programs. HTTP knowledge without transport and failure behavior is incomplete.",
    topics: [
      "Layering, packets, Ethernet, IP, forwarding, and routing",
      "Reliable byte streams, TCP state, retransmission, and flow control",
      "Congestion control, queueing, latency, throughput, and fairness",
      "DNS, HTTP, TLS boundaries, NAT, and middleboxes",
      "Sockets, packet capture, protocol design, and network debugging",
    ],
    project: "Complete the CS 144 TCP labs or build a tested TCP-like reliable stream over an unreliable local transport.",
    mastery: "You can explain a request packet-by-packet and distinguish application, transport, routing, and name-resolution failures.",
    resources: [
      {
        name: "Stanford CS 144",
        url: "https://cs144.github.io/",
        kind: "Lectures + labs",
        note: "Prioritize the programming labs; they turn TCP from a diagram into a state machine.",
      },
    ],
    prerequisites: ["c-foundations", "operating-systems"],
    progress: "planned",
    position: { x: 670, y: 974 },
  },
  {
    id: "database-systems",
    number: "02.4",
    title: "Database Systems",
    provider: "CMU 15-445",
    access: "free",
    duration: "6–9 weeks",
    effort: "8 h/week",
    summary: "Go below SQL into pages, indexes, query execution, transactions, concurrency control, logging, recovery, and distributed trade-offs.",
    why: "Using MySQL already gives useful SQL practice. Start with a diagnostic, then focus on storage, indexes, query plans, transactions, concurrency, and recovery—the layers XAMPP does not teach.",
    topics: [
      "Relational algebra, data models, normalization, and SQL execution",
      "Pages, buffers, storage layouts, B+ trees, hashing, and filters",
      "Joins, sorting, aggregation, cost models, and query optimization",
      "ACID, isolation, MVCC, locking, timestamps, and serializability",
      "Write-ahead logging, recovery, checkpoints, and parallel systems",
    ],
    project: "Reproduce isolation anomalies and inspect query plans in MySQL or PostgreSQL, then implement a page-backed B+ tree and transaction schedule checker.",
    mastery: "You can explain why a query or transaction behaves as it does without blaming the ORM or adding an index blindly.",
    resources: [
      {
        name: "CMU 15-445 Database Systems",
        url: "https://15445.courses.cs.cmu.edu/spring2026/",
        kind: "Lectures + slides + projects",
        note: "The full BusTub project is demanding; a correctly scoped subset is enough for this roadmap.",
      },
    ],
    prerequisites: ["algorithms", "operating-systems"],
    progress: "in-progress",
    position: { x: 970, y: 974 },
  },
  {
    id: "performance-engineering",
    number: "02.5",
    title: "Performance Engineering",
    provider: "MIT 6.172",
    access: "free",
    duration: "8 weeks",
    effort: "8 h/week",
    summary: "Learn to measure software, form a bottleneck hypothesis, optimize algorithms and the memory hierarchy, and prove the improvement.",
    why: "For anyone who hopes to find something more efficient, this course supplies the experimental discipline that makes the claim credible.",
    topics: [
      "Benchmark design, profiling, timing, variance, and experimental bias",
      "Compiler output, vectorization, instruction-level optimization, and SIMD",
      "Cache-aware and cache-oblivious algorithms, layout, and locality",
      "Parallelism, synchronization, races, determinism, and scalability",
      "Memory allocation, dynamic analysis, work/span, and performance reports",
    ],
    project: "Take one C program from the roadmap, establish a reproducible baseline, then make and defend one measurable optimization.",
    mastery: "You can separate algorithmic gains from compiler, cache, hardware, and measurement noise—and report negative results honestly.",
    resources: [
      {
        name: "MIT 6.172 Performance Engineering",
        url: "https://ocw.mit.edu/courses/6-172-performance-engineering-of-software-systems-fall-2018/",
        kind: "Videos + assignments + projects",
        note: "The archive is older, but measurement, cache, allocation, parallelism, and experimental method remain foundational; use current tool manuals for commands.",
      },
    ],
    prerequisites: ["algorithms", "computer-architecture", "operating-systems"],
    progress: "planned",
    position: { x: 70, y: 1244 },
  },
  {
    id: "interpreters",
    number: "02.6",
    title: "Interpreters & VMs",
    provider: "Crafting Interpreters",
    access: "free",
    duration: "8 weeks",
    effort: "7 h/week",
    summary: "Build a language twice—tree-walk and bytecode—to understand parsing, semantics, runtime representation, closures, and garbage collection.",
    why: "Programming languages stop looking fundamentally different once you have implemented the machinery underneath them.",
    topics: [
      "Lexing, parsing, grammars, syntax trees, and error recovery",
      "Names, scope, environments, functions, closures, and objects",
      "Bytecode, stack machines, instruction dispatch, and representation",
      "Memory ownership, mark-and-sweep garbage collection, and interning",
      "Language design trade-offs, testing, diagnostics, and performance",
    ],
    project: "Complete the C bytecode VM and add one deliberately small language feature with parser, runtime, tests, and a design note.",
    mastery: "You can trace source text through every compiler/runtime stage and explain the cost of a language feature.",
    resources: [
      {
        name: "Crafting Interpreters",
        url: "https://craftinginterpreters.com/",
        kind: "Complete web book",
        note: "The full book is free on the web; type the implementation instead of pasting it.",
      },
    ],
    prerequisites: ["c-foundations", "algorithms"],
    progress: "planned",
    position: { x: 370, y: 1244 },
  },
  {
    id: "web-security",
    number: "02.7",
    title: "Web & API Security",
    provider: "PortSwigger Academy",
    access: "free",
    duration: "6 weeks",
    effort: "6 h/week",
    summary: "Study authentication, authorization, injection, request handling, browser boundaries, and business-logic failures through safe labs.",
    why: "Software that handles identity, money, or private data needs security in the model—not as a framework option added at the end.",
    topics: [
      "HTTP trust boundaries, sessions, authentication, and access control",
      "SQL/command injection, path traversal, SSRF, and deserialization",
      "XSS, CSRF, CORS, browser storage, and same-origin policy",
      "OAuth, JWT, API testing, race conditions, and business logic",
      "Threat modeling, secure defaults, remediation, and verification",
    ],
    project: "Complete the server-side beginner path, then write exploit, root cause, patch, and regression check for five labs.",
    mastery: "You can identify the trust boundary and propose a server-side fix that removes the vulnerability rather than hiding its symptom.",
    resources: [
      {
        name: "Web Security Academy",
        url: "https://portswigger.net/web-security",
        kind: "Learning paths + interactive labs",
        note: "The training and labs are free; use only the intentionally vulnerable environments provided.",
      },
      {
        name: "OWASP Application Security Verification Standard",
        url: "https://owasp.org/www-project-application-security-verification-standard/",
        kind: "Verification checklist",
        note: "Use the current ASVS 5.0 requirements to turn lessons into concrete backend checks.",
      },
    ],
    prerequisites: ["computer-networks", "database-systems"],
    progress: "planned",
    position: { x: 670, y: 1244 },
  },
  {
    id: "java-core",
    number: "02.8",
    title: "Modern Java Core",
    provider: "dev.java · OpenJDK",
    access: "free",
    duration: "6 weeks",
    effort: "7 h/week",
    summary: "Learn Java as a language and runtime before learning Spring: types, objects, collections, exceptions, streams, concurrency, JVM, and tests.",
    why: "For students heading toward enterprise backend work, a short Java bridge makes framework code understandable instead of merely annotatable.",
    topics: [
      "Type system, classes, records, interfaces, generics, and immutability",
      "Collections, equality, ordering, exceptions, I/O, and serialization",
      "Lambdas, streams, pattern matching, modules, and documentation",
      "Threads, executors, futures, synchronization, and virtual threads",
      "JVM memory, garbage collection, JFR, builds, tests, and packaging",
    ],
    project: "Build a dependency-free double-entry ledger CLI using BigDecimal, file persistence, invariants, concurrency tests, and a runnable JAR.",
    mastery: "You can start from an empty directory, choose standard-library types intentionally, test invariants, inspect the JVM, and ship a small Java program.",
    resources: [
      {
        name: "Learn Java",
        url: "https://dev.java/learn/",
        kind: "Official tutorials",
        note: "Follow language, collections, streams, I/O, and virtual-thread sections before frameworks.",
      },
    ],
    prerequisites: ["composing-programs", "algorithms"],
    progress: "planned",
    position: { x: 970, y: 1244 },
  },
  {
    id: "classical-ml",
    number: "03.1",
    title: "Statistical Learning",
    provider: "ISLP · Stanford",
    access: "free",
    duration: "11 weeks",
    effort: "7 h/week",
    summary: "Learn classical ML as statistical modeling: assumptions, bias/variance, validation, regularization, trees, SVMs, and unsupervised learning.",
    why: "This is the free, rigorous main route. It puts evaluation and statistical reasoning before neural-network tooling.",
    topics: [
      "Supervised learning, loss, generalization, bias, variance, and baselines",
      "Linear and logistic models, regularization, feature selection, and inference",
      "Resampling, cross-validation, metrics, calibration, and leakage",
      "Trees, ensembles, SVMs, nonlinear methods, and interpretability",
      "PCA, clustering, unsupervised learning, and responsible experiments",
    ],
    project: "Implement linear/logistic regression and one tree split from scratch, then reproduce three ISLP labs and compare against the baseline fairly.",
    mastery: "You can state assumptions, design a leak-free evaluation, explain error sources, and defend a simple model before reaching for a larger one.",
    resources: [
      {
        name: "An Introduction to Statistical Learning · Python",
        url: "https://www.statlearning.com/",
        kind: "Free PDF + labs",
        note: "Use the Python edition and official notebooks; the companion course is also free.",
      },
    ],
    prerequisites: ["algorithms", "linear-algebra", "probability", "numerical-computing"],
    progress: "planned",
    position: { x: 70, y: 1540 },
  },
  {
    id: "andrew-ml",
    number: "03.A",
    title: "Andrew Ng ML Specialization",
    provider: "DeepLearning.AI",
    access: "mixed",
    duration: "10 weeks",
    effort: "5 h/week",
    summary: "An optional intuition-first companion covering supervised learning, neural networks, trees, unsupervised learning, and recommenders.",
    why: "You like Andrew Ng's explanations and have temporary access. Use it as a focused companion, not as a second mandatory ML curriculum.",
    topics: [
      "Regression, classification, cost functions, and gradient descent",
      "Neural networks, practical model development, and ML advice",
      "Decision trees, ensembles, bias/variance, and error analysis",
      "Clustering, anomaly detection, recommenders, and reinforcement learning",
      "Python labs that connect intuition to implementations",
    ],
    project: "During the trial, prioritize the labs and reimplement one algorithm without the course notebook; skip certificate work that adds no understanding.",
    mastery: "You can reproduce the intuition in your own words and implementation rather than recognizing it only while watching a video.",
    resources: [
      {
        name: "Machine Learning Specialization",
        url: "https://www.deeplearning.ai/specializations/machine-learning",
        kind: "Videos + labs",
        note: "Videos can be viewed free; hands-on labs and certificates require Pro or Coursera access.",
      },
    ],
    prerequisites: ["numerical-computing"],
    progress: "planned",
    position: { x: 370, y: 1540 },
  },
  {
    id: "spring-backend",
    number: "03.2",
    title: "Java Backend Fundamentals",
    provider: "Spring Guides",
    access: "free",
    duration: "6 weeks",
    effort: "8 h/week",
    summary: "Apply Java, HTTP, and database knowledge to one small backend with explicit transactions, validation, security, observability, and failure behavior.",
    why: "This narrow branch prepares students for enterprise backend work without turning a computer science roadmap into framework study.",
    topics: [
      "HTTP semantics, controllers, validation, errors, and API evolution",
      "Dependency injection, configuration, testing, and application lifecycle",
      "JDBC/JPA boundaries, transactions, isolation, locking, and idempotency",
      "Authentication, authorization, secrets, audit trails, and secure defaults",
      "Logs, metrics, tracing, health checks, packaging, and operations",
    ],
    project: "Build an idempotent transfer API with PostgreSQL, optimistic or pessimistic locking, audit records, failure tests, and no microservices.",
    mastery: "You can explain what Spring generates for you, where the transaction begins and ends, and what happens under retries, concurrency, and failure.",
    resources: [
      {
        name: "Spring Guides",
        url: "https://spring.io/guides/",
        kind: "Official guides + tutorials",
        note: "Start with REST, data access, testing, and security; build one service, not a collection of demos.",
      },
    ],
    prerequisites: ["java-core", "computer-networks", "database-systems"],
    progress: "planned",
    position: { x: 970, y: 1540 },
  },
  {
    id: "deep-learning",
    number: "03.3",
    title: "Deep Learning Foundations",
    provider: "MIT 6.S191 + D2L",
    access: "free",
    duration: "10 weeks",
    effort: "8 h/week",
    summary: "Understand optimization, neural networks, CNNs, sequence models, attention, transformers, generative models, and responsible evaluation.",
    why: "Only start after statistical learning. The point is to understand why a model trains, fails, and scales—not only how to call PyTorch.",
    topics: [
      "Computation graphs, backpropagation, optimization, initialization, and regularization",
      "MLPs, convolution, representation learning, and computer vision",
      "Sequence modeling, attention, transformers, and language models",
      "Generative modeling, autoencoders, diffusion, and latent variables",
      "Training diagnostics, generalization, data, compute, ethics, and limitations",
    ],
    project: "Write a tiny autograd engine and MLP, then reproduce one result in PyTorch with ablations and an error analysis.",
    mastery: "You can derive and inspect the training loop, explain tensor shapes and gradients, and diagnose failure before changing the architecture randomly.",
    resources: [
      {
        name: "MIT 6.S191 Introduction to Deep Learning",
        url: "https://introtodeeplearning.com/",
        kind: "Lectures + labs",
        note: "Use the current 2026 offering as a concise overview and topic map.",
      },
      {
        name: "Dive into Deep Learning",
        url: "https://d2l.ai/",
        kind: "Interactive book + code",
        note: "Use the PyTorch path and do the exercises that force shape and gradient reasoning.",
      },
    ],
    prerequisites: ["classical-ml"],
    optionalFrom: ["andrew-ml"],
    progress: "planned",
    position: { x: 70, y: 1810 },
  },
  {
    id: "distributed-systems",
    number: "03.4",
    title: "Distributed Systems",
    provider: "MIT 6.5840",
    access: "free",
    duration: "12 weeks",
    effort: "9 h/week",
    summary: "Study systems where messages delay, nodes fail, clocks disagree, and replicated state must still behave predictably.",
    why: "Serious backends eventually meet retries, duplicate requests, partitions, replication, and recovery. This is the foundation under system-design diagrams.",
    topics: [
      "RPC, partial failure, time, ordering, concurrency, and fault models",
      "Replication, primary/backup, quorum systems, and consistency models",
      "Consensus, Raft, logs, leader election, and state-machine replication",
      "Sharding, transactions, distributed storage, and recovery",
      "Papers, invariants, testing nondeterminism, and production trade-offs",
    ],
    project: "Complete the MIT Raft labs in Go and write a failure matrix that connects every test to a safety or liveness property.",
    mastery: "You can state the failure model, safety property, liveness expectation, and consistency guarantee before proposing a distributed design.",
    resources: [
      {
        name: "MIT 6.5840 Distributed Systems",
        url: "https://pdos.csail.mit.edu/6.824/",
        kind: "Lectures + papers + labs",
        note: "This is an advanced course; delay it until OS, networking, databases, and substantial programming feel solid.",
      },
    ],
    prerequisites: ["java-core", "operating-systems", "computer-networks", "database-systems"],
    progress: "planned",
    position: { x: 970, y: 1810 },
  },
  {
    id: "ml-systems",
    number: "03.5",
    title: "Machine Learning Systems",
    provider: "Full Stack Deep Learning",
    access: "free",
    duration: "8 weeks",
    effort: "7 h/week",
    summary: "Treat ML as a changing software-and-data system: scope, experiment, test, deploy, monitor, learn, and retire it responsibly.",
    why: "A model notebook is not a system. This course connects your ML branch back to databases, networking, testing, and operations.",
    topics: [
      "Problem framing, baselines, data requirements, and when not to use ML",
      "Experiment management, reproducibility, testing, and troubleshooting",
      "Data collection, labeling, versioning, validation, and lineage",
      "Serving, batching, latency, throughput, deployment, and rollback",
      "Monitoring, drift, feedback loops, continual learning, and ethics",
    ],
    project: "Ship one small model with a data contract, tests, benchmark, model card, API, monitoring signals, rollback plan, and postmortem.",
    mastery: "You can locate failures across data, model, code, infrastructure, and users—and know when a simpler non-ML system wins.",
    resources: [
      {
        name: "Full Stack Deep Learning 2022",
        url: "https://fullstackdeeplearning.com/course/2022/",
        kind: "Lectures + labs",
        note: "Keep its lifecycle and systems lessons; treat named 2022 tools as examples and check their current official documentation.",
      },
      {
        name: "Google Rules of Machine Learning",
        url: "https://developers.google.com/machine-learning/guides/rules-of-ml",
        kind: "Current engineering guide",
        note: "Use this current companion for simple baselines, reliable pipelines, measurable objectives, and production iteration.",
      },
    ],
    prerequisites: ["deep-learning", "computer-networks", "database-systems"],
    progress: "planned",
    position: { x: 370, y: 2080 },
  },
];

export const targetNode = {
  id: "original-work",
  title: "Original work loop",
  summary: "Observe → measure → reproduce → change one thing → falsify → publish.",
  position: { x: 670, y: 2390 },
  prerequisites: ["performance-engineering", "ml-systems", "distributed-systems"],
};

const ids = new Set(courses.map(({ id }) => id));

if (ids.size !== courses.length) throw new Error("Roadmap course IDs must be unique.");

for (const course of courses) {
  for (const id of [...course.prerequisites, ...(course.optionalFrom ?? [])]) {
    if (!ids.has(id)) throw new Error(`${course.id} references unknown prerequisite ${id}.`);
  }
}
